# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QQread

on:
  workflow_dispatch:
  schedule:
    - cron: '*/11 0-16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: QQread
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQREAD_BODY: ${{ secrets.QQREAD_BODY }}
        QQREAD_TIMEURL: ${{ secrets.QQREAD_TIMEURL }}
        QQREAD_TIMEHD: ${{ secrets.QQREAD_TIMEHD }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tianya908/ray
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        if: env.QQREAD_TIMEHD
        run: |
          npm install
      - name: '运行 【企鹅读书】'
        if: env.QQREAD_TIMEHD
        run: |
          node QQread.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
